[package]
name = "site-watchdog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.16"
scraper = "0.16.0"
url = "2.2"
tokio = { version = "1", features = ["full"] }
